# --- !Ups
CREATE TABLE objectcache (
  KEY varchar(100) NOT NULL,
  OBJECTDATA bytea,
  CREATEDDATE TIMESTAMP (6),
  CONSTRAINT OBJECTCACHE_PK PRIMARY KEY (KEY)
);

# --- !Downs
DROP TABLE objectcache;