# --- !Ups
CREATE TABLE CLIENT_SUMMARY (
  UNIVERSITY_ID varchar(10) NOT NULL,
  DATA text,
  VERSION timestamp(3) NOT NULL,
  CONSTRAINT PK_CLIENT_SUMMARY PRIMARY KEY (UNIVERSITY_ID)
);

CREATE TABLE CLIENT_SUMMARY_VERSION (
  UNIVERSITY_ID varchar(10) NOT NULL,
  DATA text,
  VERSION timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP timestamp(3) NOT NULL,
  CONSTRAINT PK_CLIENT_SUMMARY_VERSION PRIMARY KEY (UNIVERSITY_ID, VERSION_TIMESTAMP)
);

CREATE INDEX IDX_CLIENT_SUMMARY_VERSION ON CLIENT_SUMMARY_VERSION (UNIVERSITY_ID, VERSION);

# --- !Downs

DROP TABLE CLIENT_SUMMARY;
DROP TABLE CLIENT_SUMMARY_VERSION;