# --- !Ups

ALTER TABLE ENQUIRY ADD COLUMN CREATED_UTC timestamp NOT NULL DEFAULT localtimestamp;
ALTER TABLE ENQUIRY_VERSION ADD COLUMN CREATED_UTC timestamp NOT NULL DEFAULT localtimestamp;


# --- !Downs

ALTER TABLE ENQUIRY DROP COLUMN CREATED_UTC;
ALTER TABLE ENQUIRY_VERSION DROP COLUMN CREATED_UTC;