# --- !Ups
ALTER TABLE CLIENT_SUMMARY ADD COLUMN MENTAL_HEALTH_RISK BOOL NULL;
ALTER TABLE CLIENT_SUMMARY_VERSION ADD COLUMN MENTAL_HEALTH_RISK BOOL NULL;

# --- !Downs
ALTER TABLE CLIENT_SUMMARY DROP COLUMN MENTAL_HEALTH_RISK;
ALTER TABLE CLIENT_SUMMARY_VERSION DROP COLUMN MENTAL_HEALTH_RISK;