# --- !Ups
CREATE TABLE ENQUIRY_OWNER (
  ENQUIRY_ID uuid NOT NULL,
  UNIVERSITY_ID varchar(10) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_ENQUIRY_OWNER PRIMARY KEY (ENQUIRY_ID, UNIVERSITY_ID)
);

CREATE UNIQUE INDEX IDX_ENQUIRY_OWNER ON ENQUIRY_OWNER (ENQUIRY_ID, UNIVERSITY_ID);

CREATE TABLE ENQUIRY_OWNER_VERSION (
  ENQUIRY_ID uuid NOT NULL,
  UNIVERSITY_ID varchar(10) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_ENQUIRY_OWNER_VERSION PRIMARY KEY (ENQUIRY_ID, UNIVERSITY_ID, VERSION_TIMESTAMP_UTC)
);

# --- !Downs
DROP TABLE ENQUIRY_OWNER_VERSION;
DROP TABLE ENQUIRY_OWNER;