# --- !Ups
CREATE SEQUENCE SEQ_CASE_ID START WITH 10000000 INCREMENT BY 1;
CREATE TABLE CLIENT_CASE(
  ID UUID PRIMARY KEY,
  CREATED_UTC TIMESTAMP(3) NOT NULL,
  INCIDENT_DATE_UTC TIMESTAMP(3) NOT NULL,
  TEAM_ID VARCHAR(20) NOT NULL,
  VERSION_UTC TIMESTAMP(3) NOT NULL,
  STATE VARCHAR(100) NOT NULL,
  ON_CAMPUS BOOLEAN,
  ENQUIRY_ID UUID,
  CASE_TYPE VARCHAR(100),
  CAUSE VARCHAR(100) NOT NULL
);

CREATE TABLE CLIENT_CASE_VERSION(
  ID UUID,
  CREATED_UTC TIMESTAMP(3) NOT NULL,
  INCIDENT_DATE_UTC TIMESTAMP(3) NOT NULL,
  TEAM_ID VARCHAR(20) NOT NULL,
  VERSION_UTC TIMESTAMP(3) NOT NULL,
  STATE VARCHAR(100) NOT NULL,
  ON_CAMPUS BOOLEAN,
  ENQUIRY_ID UUID,
  CASE_TYPE VARCHAR(100),
  CAUSE VARCHAR(100) NOT NULL,
  VERSION_OPERATION CHAR(6) NOT NULL,
  VERSION_TIMESTAMP_UTC TIMESTAMP(3) NOT NULL,
  CONSTRAINT PK_CASE_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

# --- !Downs

DROP TABLE CLIENT_CASE_VERSION;
DROP TABLE CLIENT_CASE;
DROP SEQUENCE SEQ_CASE_ID;