# --- !Ups
CREATE TABLE OWNER (
  ENTITY_ID uuid NOT NULL,
  ENTITY_TYPE VARCHAR(100) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_OWNER PRIMARY KEY (ENTITY_ID, ENTITY_TYPE, USER_ID)
);

CREATE UNIQUE INDEX IDX_OWNER ON OWNER (ENTITY_ID, ENTITY_TYPE, USER_ID);

CREATE TABLE OWNER_VERSION (
  ENTITY_ID uuid NOT NULL,
  ENTITY_TYPE VARCHAR(100) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_OWNER_VERSION PRIMARY KEY (ENTITY_ID, ENTITY_TYPE, USER_ID, VERSION_TIMESTAMP_UTC)
);

# --- !Downs
DROP TABLE OWNER_VERSION;
DROP TABLE OWNER;
