# --- !Ups
CREATE TABLE AUDIT_EVENT (
	"ID" raw(32) NOT NULL,
  "EVENT_DATE" timestamp NOT NULL,
  "OPERATION" nvarchar2(255) NOT NULL,
  "USERCODE" nvarchar2(255),
  "DATA" nclob,
  "TARGET_ID" nvarchar2(255) NOT NULL,
  "TARGET_TYPE" nvarchar2(255) NOT NULL,
  CONSTRAINT "AUDIT_EVENT_PK" PRIMARY KEY ("ID")
);

CREATE INDEX IDX_AUDIT_EVENT_FK ON AUDIT_EVENT (TARGET_ID, TARGET_TYPE);

# --- !Downs
DROP TABLE AUDIT_EVENT;