# --- !Ups
CREATE TABLE CLIENT_CASE_TAG (
  CASE_ID uuid NOT NULL,
  TAG VARCHAR(100) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_TAG PRIMARY KEY (CASE_ID, TAG),
  CONSTRAINT FK_CASE_TAG FOREIGN KEY (CASE_ID) REFERENCES CLIENT_CASE (ID) ON DELETE RESTRICT
);

CREATE INDEX IDX_CASE_TAG ON CLIENT_CASE_TAG (CASE_ID);

CREATE TABLE CLIENT_CASE_TAG_VERSION (
  CASE_ID uuid NOT NULL,
  TAG VARCHAR(100) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_TAG_VERSION PRIMARY KEY (CASE_ID, TAG, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_CASE_TAG_VERSION ON CLIENT_CASE_TAG_VERSION (CASE_ID, TAG, VERSION_UTC);

# --- !Downs
DROP TABLE CLIENT_CASE_TAG_VERSION;
DROP TABLE CLIENT_CASE_TAG;
