# --- !Ups
ALTER TABLE CLIENT_CASE ADD COLUMN CASE_KEY varchar(10) NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ADD COLUMN CASE_KEY varchar(10) NOT NULL;
CREATE UNIQUE INDEX IDX_CLIENT_CASE_KEY ON CLIENT_CASE (CASE_KEY);

CREATE TABLE CLIENT_CASE_CLIENT (
  CASE_ID uuid NOT NULL,
  UNIVERSITY_ID VARCHAR(10) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_CLIENT PRIMARY KEY (CASE_ID, UNIVERSITY_ID),
  CONSTRAINT FK_CASE_CLIENT FOREIGN KEY (CASE_ID) REFERENCES CLIENT_CASE (ID) ON DELETE RESTRICT
);

CREATE INDEX IDX_CASE_CLIENT ON CLIENT_CASE_CLIENT (CASE_ID);
CREATE INDEX IDX_CASE_CLIENT_UNIVERSITY_ID ON CLIENT_CASE_CLIENT (UNIVERSITY_ID);

CREATE TABLE CLIENT_CASE_CLIENT_VERSION (
  CASE_ID uuid NOT NULL,
  UNIVERSITY_ID VARCHAR(10) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_CLIENT_VERSION PRIMARY KEY (CASE_ID, UNIVERSITY_ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_CASE_CLIENT_VERSION ON CLIENT_CASE_CLIENT_VERSION (CASE_ID, UNIVERSITY_ID, VERSION_UTC);

# --- !Downs
ALTER TABLE CLIENT_CASE DROP COLUMN CASE_KEY;
ALTER TABLE CLIENT_CASE_VERSION DROP COLUMN CASE_KEY;

DROP TABLE CLIENT_CASE_CLIENT_VERSION;
DROP TABLE CLIENT_CASE_CLIENT;