# --- !Ups
ALTER TABLE CLIENT_CASE ALTER COLUMN ON_CAMPUS SET DEFAULT FALSE;
ALTER TABLE CLIENT_CASE ALTER COLUMN ON_CAMPUS SET NOT NULL;
ALTER TABLE CLIENT_CASE ADD COLUMN NOTIFIED_POLICE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CLIENT_CASE ADD COLUMN NOTIFIED_AMBULANCE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CLIENT_CASE ADD COLUMN NOTIFIED_FIRE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CLIENT_CASE ALTER COLUMN ON_CAMPUS DROP DEFAULT;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_POLICE DROP DEFAULT;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_AMBULANCE DROP DEFAULT;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_FIRE DROP DEFAULT;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN ON_CAMPUS SET DEFAULT FALSE;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN ON_CAMPUS SET NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ADD COLUMN NOTIFIED_POLICE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CLIENT_CASE_VERSION ADD COLUMN NOTIFIED_AMBULANCE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CLIENT_CASE_VERSION ADD COLUMN NOTIFIED_FIRE BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN ON_CAMPUS DROP DEFAULT;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_POLICE DROP DEFAULT;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_AMBULANCE DROP DEFAULT;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_FIRE DROP DEFAULT;

# --- !Downs
ALTER TABLE CLIENT_CASE ALTER COLUMN ON_CAMPUS DROP NOT NULL;
ALTER TABLE CLIENT_CASE DROP COLUMN NOTIFIED_POLICE;
ALTER TABLE CLIENT_CASE DROP COLUMN NOTIFIED_AMBULANCE;
ALTER TABLE CLIENT_CASE DROP COLUMN NOTIFIED_FIRE;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN ON_CAMPUS DROP NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION DROP COLUMN NOTIFIED_POLICE;
ALTER TABLE CLIENT_CASE_VERSION DROP COLUMN NOTIFIED_AMBULANCE;
ALTER TABLE CLIENT_CASE_VERSION DROP COLUMN NOTIFIED_FIRE;