# --- !Ups
CREATE TABLE CLIENT_CASE_NOTE (
  ID uuid NOT NULL,
  CASE_ID uuid NOT NULL,
  NOTE_TYPE varchar(20) NOT NULL,
  TEXT text NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_NOTE PRIMARY KEY (ID),
  CONSTRAINT FK_CASE_NOTE FOREIGN KEY (CASE_ID) REFERENCES CLIENT_CASE (ID) ON DELETE RESTRICT
);

CREATE INDEX IDX_CASE_NOTE ON CLIENT_CASE_NOTE (CASE_ID);

CREATE TABLE CLIENT_CASE_NOTE_VERSION (
  ID uuid NOT NULL,
  CASE_ID uuid NOT NULL,
  NOTE_TYPE varchar(20) NOT NULL,
  TEXT text NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_NOTE_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_CASE_NOTE_VERSION ON CLIENT_CASE_NOTE_VERSION (ID, VERSION_UTC);

# --- !Downs
DROP TABLE CLIENT_CASE_NOTE_VERSION;
DROP TABLE CLIENT_CASE_NOTE;
