# --- !Ups
CREATE TABLE UPLOADED_FILE (
  ID uuid NOT NULL,
  FILE_NAME varchar(200) NOT NULL,
  CONTENT_LENGTH bigint NOT NULL,
  CONTENT_TYPE varchar(200) NOT NULL,
  UPLOADED_BY varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_UPLOADED_FILE PRIMARY KEY (ID)
);

CREATE TABLE UPLOADED_FILE_VERSION (
  ID uuid NOT NULL,
  FILE_NAME varchar(200) NOT NULL,
  CONTENT_LENGTH bigint NOT NULL,
  CONTENT_TYPE varchar(200) NOT NULL,
  UPLOADED_BY varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_UPLOADED_FILE_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_UPLOADED_FILE_VERSION ON UPLOADED_FILE_VERSION (ID, VERSION_UTC);

CREATE TABLE CLIENT_CASE_DOCUMENT (
  ID uuid NOT NULL,
  CASE_ID uuid NOT NULL,
  DOCUMENT_TYPE varchar(40) NOT NULL,
  FILE_ID uuid NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_DOCUMENT PRIMARY KEY (ID),
  CONSTRAINT FK_CASE_DOCUMENT_CASE FOREIGN KEY (CASE_ID) REFERENCES CLIENT_CASE (ID) ON DELETE RESTRICT,
  CONSTRAINT FK_CASE_DOCUMENT_FILE FOREIGN KEY (FILE_ID) REFERENCES UPLOADED_FILE (ID) ON DELETE RESTRICT
);

CREATE INDEX IDX_CASE_DOCUMENT_CASE ON CLIENT_CASE_DOCUMENT (CASE_ID);
CREATE INDEX IDX_CASE_DOCUMENT_FILE ON CLIENT_CASE_DOCUMENT (FILE_ID);

CREATE TABLE CLIENT_CASE_DOCUMENT_VERSION (
  ID uuid NOT NULL,
  CASE_ID uuid NOT NULL,
  DOCUMENT_TYPE varchar(40) NOT NULL,
  FILE_ID uuid NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CASE_DOCUMENT_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_CASE_DOCUMENT_VERSION ON CLIENT_CASE_DOCUMENT_VERSION (ID, VERSION_UTC);

# --- !Downs
DROP TABLE CLIENT_CASE_DOCUMENT_VERSION;
DROP TABLE CLIENT_CASE_DOCUMENT;
DROP TABLE UPLOADED_FILE_VERSION;
DROP TABLE UPLOADED_FILE;