# --- !Ups
ALTER TABLE CLIENT_CASE ALTER COLUMN INCIDENT_DATE_UTC DROP NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN ON_CAMPUS DROP NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_POLICE DROP NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_AMBULANCE DROP NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_FIRE DROP NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN INCIDENT_DATE_UTC DROP NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN ON_CAMPUS DROP NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_POLICE DROP NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_AMBULANCE DROP NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_FIRE DROP NOT NULL;

# --- !Downs
ALTER TABLE CLIENT_CASE ALTER COLUMN INCIDENT_DATE_UTC SET NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN ON_CAMPUS SET NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_POLICE SET NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_AMBULANCE SET NOT NULL;
ALTER TABLE CLIENT_CASE ALTER COLUMN NOTIFIED_FIRE SET NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN INCIDENT_DATE_UTC SET NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN ON_CAMPUS SET NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_POLICE SET NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_AMBULANCE SET NOT NULL;
ALTER TABLE CLIENT_CASE_VERSION ALTER COLUMN NOTIFIED_FIRE SET NOT NULL;