# --- !Ups
ALTER TABLE MESSAGE ADD FILE_ID uuid;
ALTER TABLE MESSAGE_VERSION ADD FILE_ID uuid;

ALTER TABLE MESSAGE ADD CONSTRAINT FK_MESSAGE_FILE FOREIGN KEY (FILE_ID) REFERENCES UPLOADED_FILE (ID) ON DELETE RESTRICT;
CREATE INDEX IDX_MESSAGE_FILE ON MESSAGE (FILE_ID);

# --- !Downs
ALTER TABLE MESSAGE DROP COLUMN FILE_ID;
ALTER TABLE MESSAGE_VERSION DROP COLUMN FILE_ID;
