# --- !Ups
ALTER TABLE UPLOADED_FILE ADD OWNER_ID uuid;
ALTER TABLE UPLOADED_FILE ADD OWNER_TYPE varchar(20);
ALTER TABLE UPLOADED_FILE_VERSION ADD OWNER_ID uuid;
ALTER TABLE UPLOADED_FILE_VERSION ADD OWNER_TYPE varchar(20);

CREATE INDEX IDX_UPLOADED_FILE_OWNER ON UPLOADED_FILE (OWNER_ID, OWNER_TYPE);

# --- !Downs
ALTER TABLE UPLOADED_FILE DROP COLUMN OWNER_ID;
ALTER TABLE UPLOADED_FILE DROP COLUMN OWNER_TYPE;
ALTER TABLE UPLOADED_FILE_VERSION DROP COLUMN OWNER_ID;
ALTER TABLE UPLOADED_FILE_VERSION DROP COLUMN OWNER_TYPE;
