# --- !Ups
ALTER TABLE MESSAGE ADD TEAM_ID varchar(20);
ALTER TABLE MESSAGE_VERSION ADD TEAM_ID varchar(20);

# --- !Downs
ALTER TABLE MESSAGE DROP COLUMN TEAM_ID;
ALTER TABLE MESSAGE_VERSION DROP COLUMN TEAM_ID;
