# --- !Ups
CREATE TABLE ENQUIRY_NOTE (
  ID uuid NOT NULL,
  ENQUIRY_ID uuid NOT NULL,
  NOTE_TYPE varchar(20) NOT NULL,
  TEXT text NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_ENQUIRY_NOTE PRIMARY KEY (ID),
  CONSTRAINT FK_ENQUIRY_NOTE FOREIGN KEY (ENQUIRY_ID) REFERENCES ENQUIRY (ID) ON DELETE RESTRICT
);

CREATE INDEX IDX_ENQUIRY_NOTE ON ENQUIRY_NOTE (ENQUIRY_ID);

CREATE TABLE ENQUIRY_NOTE_VERSION (
  ID uuid NOT NULL,
  ENQUIRY_ID uuid NOT NULL,
  NOTE_TYPE varchar(20) NOT NULL,
  TEXT text NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_ENQUIRY_NOTE_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_ENQUIRY_NOTE_VERSION ON ENQUIRY_NOTE_VERSION (ID, VERSION_UTC);

# --- !Downs
DROP TABLE ENQUIRY_NOTE_VERSION;
DROP TABLE ENQUIRY_NOTE;
