# --- !Ups
DELETE FROM CLIENT_CASE_LINK;
ALTER TABLE CLIENT_CASE_LINK ADD COLUMN ID UUID NOT NULL;
ALTER TABLE CLIENT_CASE_LINK DROP CONSTRAINT PK_CASE_LINK;
ALTER TABLE CLIENT_CASE_LINK ADD CONSTRAINT PK_CASE_LINK PRIMARY KEY (ID);
ALTER TABLE CLIENT_CASE_LINK ADD CONSTRAINT CASE_LINK_UNIQUE UNIQUE (LINK_TYPE, OUTGOING_CASE_ID, INCOMING_CASE_ID);

DELETE FROM CLIENT_CASE_LINK_VERSION;
ALTER TABLE CLIENT_CASE_LINK_VERSION ADD COLUMN ID UUID NOT NULL;
ALTER TABLE CLIENT_CASE_LINK_VERSION DROP CONSTRAINT PK_CASE_LINK_VERSION;
ALTER TABLE CLIENT_CASE_LINK_VERSION ADD CONSTRAINT PK_CASE_LINK_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC);
ALTER TABLE CLIENT_CASE_LINK_VERSION ADD CONSTRAINT CASE_LINK_VERSION_UNIQUE UNIQUE (LINK_TYPE, OUTGOING_CASE_ID, INCOMING_CASE_ID, VERSION_TIMESTAMP_UTC);

# --- !Downs
ALTER TABLE CLIENT_CASE_LINK DROP COLUMN ID;
ALTER TABLE CLIENT_CASE_LINK DROP CONSTRAINT CASE_LINK_UNIQUE;
ALTER TABLE CLIENT_CASE_LINK ADD CONSTRAINT PK_CASE_LINK PRIMARY KEY (LINK_TYPE, OUTGOING_CASE_ID, INCOMING_CASE_ID);
ALTER TABLE CLIENT_CASE_LINK_VERSION DROP COLUMN ID;
ALTER TABLE CLIENT_CASE_LINK_VERSION DROP CONSTRAINT CASE_LINK_VERSION_UNIQUE;
ALTER TABLE CLIENT_CASE_LINK_VERSION ADD CONSTRAINT PK_CASE_LINK_VERSION PRIMARY KEY (LINK_TYPE, OUTGOING_CASE_ID, INCOMING_CASE_ID, VERSION_TIMESTAMP_UTC);