# --- !Ups
DELETE FROM CLIENT_CASE_LINK;
ALTER TABLE CLIENT_CASE_LINK ADD COLUMN CASE_NOTE uuid NOT NULL;
ALTER TABLE CLIENT_CASE_LINK ADD COLUMN TEAM_MEMBER VARCHAR(100) NOT NULL;
ALTER TABLE CLIENT_CASE_LINK ADD CONSTRAINT FK_CASE_LINK_NOTE FOREIGN KEY (CASE_NOTE) REFERENCES CLIENT_CASE_NOTE (ID) ON DELETE RESTRICT;

DELETE FROM CLIENT_CASE_LINK_VERSION;
ALTER TABLE CLIENT_CASE_LINK_VERSION ADD COLUMN CASE_NOTE uuid NOT NULL;
ALTER TABLE CLIENT_CASE_LINK_VERSION ADD COLUMN TEAM_MEMBER VARCHAR(100) NOT NULL;

DELETE FROM CLIENT_CASE_DOCUMENT;
ALTER TABLE CLIENT_CASE_DOCUMENT ADD COLUMN CASE_NOTE uuid NOT NULL;
ALTER TABLE CLIENT_CASE_DOCUMENT ADD CONSTRAINT FK_CASE_DOCUMENT_NOTE FOREIGN KEY (CASE_NOTE) REFERENCES CLIENT_CASE_NOTE (ID) ON DELETE RESTRICT;

DELETE FROM CLIENT_CASE_DOCUMENT_VERSION;
ALTER TABLE CLIENT_CASE_DOCUMENT_VERSION ADD COLUMN CASE_NOTE uuid NOT NULL;


# --- !Downs
ALTER TABLE CLIENT_CASE_LINK DROP COLUMN CASE_NOTE;
ALTER TABLE CLIENT_CASE_LINK DROP COLUMN TEAM_MEMBER;
ALTER TABLE CLIENT_CASE_LINK_VERSION DROP COLUMN CASE_NOTE;
ALTER TABLE CLIENT_CASE_LINK_VERSION DROP COLUMN TEAM_MEMBER;

ALTER TABLE CLIENT_CASE_DOCUMENT DROP COLUMN CASE_NOTE;
ALTER TABLE CLIENT_CASE_DOCUMENT_VERSION DROP COLUMN CASE_NOTE;