# --- !Ups

ALTER TABLE APPOINTMENT DROP COLUMN subject;
ALTER TABLE APPOINTMENT_VERSION DROP COLUMN subject;

# --- !Downs

ALTER TABLE APPOINTMENT ADD COLUMN subject varchar(200);
ALTER TABLE APPOINTMENT_VERSION ADD COLUMN subject varchar(200);