# --- !Ups
CREATE TABLE CLIENT (
  UNIVERSITY_ID varchar(20) NOT NULL,
  FULL_NAME varchar(100) NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_CLIENT PRIMARY KEY (UNIVERSITY_ID)
);

CREATE TABLE CLIENT_VERSION (
  UNIVERSITY_ID varchar(20) NOT NULL,
  FULL_NAME varchar(100) NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  VERSION_USER VARCHAR(100) NULL,
  CONSTRAINT PK_CLIENT_VERSION PRIMARY KEY (UNIVERSITY_ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_CLIENT_VERSION ON CLIENT_VERSION (UNIVERSITY_ID, VERSION_UTC);

INSERT INTO CLIENT
SELECT DISTINCT UNIVERSITY_ID, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM APPOINTMENT_CLIENT;

ALTER TABLE APPOINTMENT_CLIENT ADD CONSTRAINT FK_APPOINTMENT_CLIENT_CLIENT FOREIGN KEY (UNIVERSITY_ID) REFERENCES CLIENT(UNIVERSITY_ID);

INSERT INTO CLIENT
SELECT DISTINCT UNIVERSITY_ID, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM CLIENT_CASE_CLIENT WHERE UNIVERSITY_ID NOT IN (SELECT UNIVERSITY_ID FROM CLIENT);

ALTER TABLE CLIENT_CASE_CLIENT ADD CONSTRAINT FK_CLIENT_CASE_CLIENT_CLIENT FOREIGN KEY (UNIVERSITY_ID) REFERENCES CLIENT(UNIVERSITY_ID);

INSERT INTO CLIENT
SELECT DISTINCT UNIVERSITY_ID, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM CLIENT_SUMMARY WHERE UNIVERSITY_ID NOT IN (SELECT UNIVERSITY_ID FROM CLIENT);

ALTER TABLE CLIENT_SUMMARY ADD CONSTRAINT FK_CLIENT_SUMMARY_CLIENT FOREIGN KEY (UNIVERSITY_ID) REFERENCES CLIENT(UNIVERSITY_ID);

INSERT INTO CLIENT
SELECT DISTINCT UNIVERSITY_ID, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM ENQUIRY WHERE UNIVERSITY_ID NOT IN (SELECT UNIVERSITY_ID FROM CLIENT);

ALTER TABLE ENQUIRY ADD CONSTRAINT FK_ENQUIRY_CLIENT FOREIGN KEY (UNIVERSITY_ID) REFERENCES CLIENT(UNIVERSITY_ID);

# --- !Downs
ALTER TABLE APPOINTMENT_CLIENT DROP CONSTRAINT FK_APPOINTMENT_CLIENT_CLIENT;
ALTER TABLE CLIENT_CASE_CLIENT DROP CONSTRAINT FK_CLIENT_CASE_CLIENT_CLIENT;
ALTER TABLE CLIENT_SUMMARY DROP CONSTRAINT FK_CLIENT_SUMMARY_CLIENT;
ALTER TABLE ENQUIRY DROP CONSTRAINT FK_ENQUIRY_CLIENT;

DROP TABLE CLIENT_VERSION;
DROP TABLE CLIENT;

