# --- !Ups
CREATE TABLE MEMBER (
  USER_ID varchar(255) NOT NULL,
  FULL_NAME varchar(100) NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_MEMBER PRIMARY KEY (USER_ID)
);

CREATE TABLE MEMBER_VERSION (
  USER_ID varchar(255) NOT NULL,
  FULL_NAME varchar(100) NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  VERSION_USER VARCHAR(100) NULL,
  CONSTRAINT PK_MEMBER_VERSION PRIMARY KEY (USER_ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_MEMBER_VERSION ON MEMBER_VERSION (USER_ID, VERSION_UTC);

INSERT INTO MEMBER
SELECT DISTINCT TEAM_MEMBER, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM APPOINTMENT;

ALTER TABLE APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER(USER_ID);

INSERT INTO MEMBER
SELECT DISTINCT TEAM_MEMBER, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM APPOINTMENT_NOTE WHERE TEAM_MEMBER NOT IN (SELECT USER_ID FROM MEMBER);

ALTER TABLE APPOINTMENT_NOTE ADD CONSTRAINT FK_APPOINTMENT_NOTE_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER(USER_ID);

INSERT INTO MEMBER
SELECT DISTINCT TEAM_MEMBER, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM CLIENT_CASE_DOCUMENT WHERE TEAM_MEMBER NOT IN (SELECT USER_ID FROM MEMBER);

ALTER TABLE CLIENT_CASE_DOCUMENT ADD CONSTRAINT FK_CLIENT_CASE_DOCUMENT_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER(USER_ID);

INSERT INTO MEMBER
SELECT DISTINCT TEAM_MEMBER, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM CLIENT_CASE_LINK WHERE TEAM_MEMBER NOT IN (SELECT USER_ID FROM MEMBER);

ALTER TABLE CLIENT_CASE_LINK ADD CONSTRAINT FK_CLIENT_CASE_LINK_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER(USER_ID);

INSERT INTO MEMBER
SELECT DISTINCT TEAM_MEMBER, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM CLIENT_CASE_NOTE WHERE TEAM_MEMBER NOT IN (SELECT USER_ID FROM MEMBER);

ALTER TABLE CLIENT_CASE_NOTE ADD CONSTRAINT FK_CLIENT_CASE_NOTE_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER(USER_ID);

INSERT INTO MEMBER
SELECT DISTINCT TEAM_MEMBER, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM ENQUIRY_NOTE WHERE TEAM_MEMBER NOT IN (SELECT USER_ID FROM MEMBER);

ALTER TABLE ENQUIRY_NOTE ADD CONSTRAINT FK_ENQUIRY_NOTE_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER(USER_ID);

INSERT INTO MEMBER
SELECT DISTINCT TEAM_MEMBER, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM MESSAGE WHERE TEAM_MEMBER NOT IN (SELECT USER_ID FROM MEMBER);

ALTER TABLE MESSAGE ADD CONSTRAINT FK_MESSAGE_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER(USER_ID);

INSERT INTO MEMBER
SELECT DISTINCT USER_ID, NULL, to_timestamp('01/01/70 00:00', 'DD/MM/YY HH24:MI')
FROM OWNER WHERE USER_ID NOT IN (SELECT USER_ID FROM MEMBER);

ALTER TABLE OWNER ADD CONSTRAINT FK_OWNER_USER_ID_MEMBER FOREIGN KEY (USER_ID) REFERENCES MEMBER(USER_ID);

# --- !Downs
ALTER TABLE OWNER DROP CONSTRAINT FK_OWNER_USER_ID_MEMBER;
ALTER TABLE MESSAGE DROP CONSTRAINT FK_MESSAGE_TEAM_MEMBER_MEMBER;
ALTER TABLE ENQUIRY_NOTE DROP CONSTRAINT FK_ENQUIRY_NOTE_TEAM_MEMBER_MEMBER;
ALTER TABLE CLIENT_CASE_NOTE DROP CONSTRAINT FK_CLIENT_CASE_NOTE_TEAM_MEMBER_MEMBER;
ALTER TABLE CLIENT_CASE_LINK DROP CONSTRAINT FK_CLIENT_CASE_LINK_TEAM_MEMBER_MEMBER;
ALTER TABLE CLIENT_CASE_DOCUMENT DROP CONSTRAINT FK_CLIENT_CASE_DOCUMENT_TEAM_MEMBER_MEMBER;
ALTER TABLE APPOINTMENT_NOTE DROP CONSTRAINT FK_APPOINTMENT_NOTE_TEAM_MEMBER_MEMBER;
ALTER TABLE APPOINTMENT DROP CONSTRAINT FK_APPOINTMENT_TEAM_MEMBER_MEMBER;

DROP TABLE MEMBER_VERSION;
DROP TABLE MEMBER;

