# --- !Ups
ALTER TABLE USER_REGISTRATION ADD COLUMN LAST_INVITED_UTC timestamp(3) DEFAULT current_date NOT NULL;
ALTER TABLE USER_REGISTRATION_VERSION ADD COLUMN LAST_INVITED_UTC timestamp(3) DEFAULT current_date NOT NULL;

# --- !Downs
ALTER TABLE USER_REGISTRATION DROP COLUMN LAST_INVITED_UTC;
ALTER TABLE USER_REGISTRATION_VERSION DROP COLUMN LAST_INVITED_UTC;

# --- !Ups
update client_case set case_type = null;

# --- !Downs