# --- !Ups
ALTER TABLE AUDIT_EVENT ALTER COLUMN ID TYPE uuid using id::uuid;
ALTER TABLE USER_REGISTRATION ALTER COLUMN ID TYPE uuid using id::uuid;

# --- !Downs
ALTER TABLE AUDIT_EVENT ALTER COLUMN ID TYPE varchar(100);
ALTER TABLE USER_REGISTRATION ALTER COLUMN ID TYPE varchar(100);