# --- !Ups
DROP TABLE APPOINTMENT_NOTE_VERSION;
DROP TABLE APPOINTMENT_NOTE;

# --- !Downs
CREATE TABLE APPOINTMENT_NOTE (
  ID uuid NOT NULL,
  APPOINTMENT_ID uuid NOT NULL,
  TEXT text NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  CONSTRAINT PK_APPOINTMENT_NOTE PRIMARY KEY (ID),
  CONSTRAINT FK_APPOINTMENT_NOTE FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT (ID) ON DELETE RESTRICT,
  CONSTRAINT FK_APPOINTMENT_NOTE_TEAM_MEMBER_MEMBER FOREIGN KEY (TEAM_MEMBER) REFERENCES MEMBER (USER_ID),
);

CREATE INDEX IDX_APPOINTMENT_NOTE ON APPOINTMENT_NOTE (APPOINTMENT_ID);

CREATE TABLE APPOINTMENT_NOTE_VERSION (
  ID uuid NOT NULL,
  APPOINTMENT_ID uuid NOT NULL,
  TEXT text NOT NULL,
  TEAM_MEMBER varchar(100) NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  VERSION_UTC timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP_UTC timestamp(3) NOT NULL,
  VERSION_USER VARCHAR(100) NULL,
  CONSTRAINT PK_APPOINTMENT_NOTE_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP_UTC)
);

CREATE INDEX IDX_APPOINTMENT_NOTE_VERSION ON APPOINTMENT_NOTE_VERSION (ID, VERSION_UTC);
