# --- !Ups
CREATE TABLE ENQUIRY (
  ID uuid NOT NULL,
  UNIVERSITY_ID varchar(10) NOT NULL,
  TEAM_ID varchar(20) NOT NULL,
  VERSION timestamp(3) NOT NULL,
  CONSTRAINT PK_ENQUIRY PRIMARY KEY (ID)
);

CREATE TABLE ENQUIRY_VERSION (
  ID uuid NOT NULL,
  UNIVERSITY_ID varchar(10) NOT NULL,
  TEAM_ID varchar(20) NOT NULL,
  VERSION timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP timestamp(3) NOT NULL,
  CONSTRAINT PK_ENQUIRY_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP)
);


CREATE TABLE MESSAGE (
  ID uuid NOT NULL,
  SENDER varchar(20) NOT NULL,
  TEXT text NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  OWNER_ID uuid NOT NULL,
  OWNER_TYPE varchar(20) NOT NULL,
  VERSION timestamp(3) NOT NULL,
  CONSTRAINT PK_MESSAGE PRIMARY KEY (ID)
);

CREATE TABLE MESSAGE_VERSION (
  ID uuid NOT NULL,
  SENDER varchar(20) NOT NULL,
  TEXT text NOT NULL,
  CREATED_UTC timestamp(3) NOT NULL,
  OWNER_ID uuid NOT NULL,
  OWNER_TYPE varchar(20) NOT NULL,
  VERSION timestamp(3) NOT NULL,
  VERSION_OPERATION char(6) NOT NULL,
  VERSION_TIMESTAMP timestamp(3) NOT NULL,
  CONSTRAINT PK_MESSAGE_VERSION PRIMARY KEY (ID, VERSION_TIMESTAMP)
);

# --- !Downs
DROP TABLE ENQUIRY;
DROP TABLE ENQUIRY_VERSION;
DROP TABLE MESSAGE;
DROP TABLE MESSAGE_VERSION;