# --- !Ups

ALTER TABLE ENQUIRY ADD COLUMN STATE VARCHAR(20) NOT NULL DEFAULT 'Open';
ALTER TABLE ENQUIRY_VERSION ADD COLUMN STATE VARCHAR(20) NOT NULL DEFAULT 'Open';

-- Team member sending oo receiving this message.
ALTER TABLE MESSAGE ADD COLUMN TEAM_MEMBER VARCHAR(100);
ALTER TABLE MESSAGE_VERSION ADD COLUMN TEAM_MEMBER VARCHAR(100);

-- Messages to/from clients.
-- Treating message_client as immutable (never changed or deleted for a given message_id)
-- so no version table required.
CREATE TABLE MESSAGE_CLIENT (
  ID uuid NOT NULL,
  UNIVERSITY_ID varchar(20),
  MESSAGE_ID uuid NOT NULL,
  CONSTRAINT PK_MESSAGE_RECIPIENT PRIMARY KEY (ID)
);

CREATE INDEX IDX_MESSAGE_CLIENT_MID ON MESSAGE_CLIENT(MESSAGE_ID);

# --- !Downs

ALTER TABLE MESSAGE DROP COLUMN TEAM_MEMBER;
ALTER TABLE MESSAGE_VERSION DROP COLUMN TEAM_MEMBER;

ALTER TABLE ENQUIRY DROP COLUMN STATE;
ALTER TABLE ENQUIRY_VERSION DROP COLUMN STATE;

DROP INDEX IDX_MESSAGE_CLIENT_MID;
DROP TABLE MESSAGE_CLIENT;