package domain.dao

import slick.lifted.MappedTo

/**
  * Wrapper for type of ID column that is an autogenerated string.
  *
  * Extending MappedTo means it doesn't need a separate mapping definition.
  */
case class GeneratedId(value: String) extends MappedTo[String]
