# --- !Ups
CREATE SEQUENCE SEQ_ENQUIRY_KEY START WITH 1000 INCREMENT BY 1;

ALTER TABLE ENQUIRY ADD COLUMN ENQUIRY_KEY varchar(10) NOT NULL;
ALTER TABLE ENQUIRY_VERSION ADD COLUMN ENQUIRY_KEY varchar(10) NOT NULL;

CREATE UNIQUE INDEX IDX_ENQUIRY_KEY ON ENQUIRY (ENQUIRY_KEY);

# --- !Downs
DROP SEQUENCE SEQ_ENQUIRY_KEY;

ALTER TABLE ENQUIRY DROP COLUMN ENQUIRY_KEY;
ALTER TABLE ENQUIRY_VERSION DROP COLUMN ENQUIRY_KEY;